name: "Churn Predictor CI"

on:
  push:
    branches:
      - main

jobs:
  lint_test_predictor:
    name: "Lint and Test Churn Predictor CI"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
          architecture: x64

      - name: Install dependencies
        run: make install

      - name: Lint Churn Library
        run: make lint

      - name: Test Churn Library
        run: make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Churn Library Tests
          path: pytest.xml

  publish_test_results:
    name: "Publish Churn Library Test Results"
    needs: lint_test_predictor
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
