name: "Churn Predictor CI"

on:
  push:
    branches:
      - main

jobs:
  lint_test_predictor:
    name: "Lint and Test Churn Predictor CI"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
          architecture: x64

      - name: Install dependencies
        run: make install

      - name: Lint Churn Library
        run: make lint

      - name: Test Churn Library
        run: make test
